#!/usr/bin/env node

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

import { Command } from 'commander';

import { syncGoogleAdsCatalog } from '../../spec/src/index.js';
import { buildGoogleAdsRequest } from '../../core/src/index.js';

import type { SyncedGoogleAdsCatalog } from '../../spec/src/index.js';
import type { OperationDescriptor } from '../../core/src/index.js';

export interface CliDependencies {
  syncCatalog?: (options: { version: string }) => Promise<SyncedGoogleAdsCatalog>;
  loadOperationsCatalog?: (path: string) => Promise<OperationDescriptor[]>;
  stdout?: Pick<NodeJS.WriteStream, 'write'>;
}

async function writeCatalogOutputs(
  outDir: string,
  catalog: SyncedGoogleAdsCatalog
): Promise<void> {
  await mkdir(outDir, { recursive: true });
  await Promise.all([
    writeFile(join(outDir, 'operations.json'), JSON.stringify(catalog.operations, null, 2)),
    writeFile(join(outDir, 'docs-catalog.json'), JSON.stringify(catalog.docsEntries, null, 2)),
    writeFile(join(outDir, 'coverage.json'), JSON.stringify(catalog.coverage, null, 2))
  ]);
}

export async function runCli(
  argv: string[],
  dependencies: CliDependencies = {}
): Promise<number> {
  const program = new Command();
  const stdout = dependencies.stdout ?? process.stdout;
  const syncCatalog =
    dependencies.syncCatalog ?? ((options: { version: string }) => syncGoogleAdsCatalog(options));
  const loadOperationsCatalog =
    dependencies.loadOperationsCatalog ??
    (async (path: string) =>
      JSON.parse(await readFile(path, 'utf8')) as OperationDescriptor[]);

  program.name('gads');

  const docs = program
    .command('docs')
    .description('Work with normalized Google Ads documentation artifacts');

  docs
    .command('sync')
    .requiredOption('--version <version>', 'Google Ads API version', 'v22')
    .requiredOption('--out-dir <outDir>', 'Directory to write normalized artifacts')
    .action(async (options: { version: string; outDir: string }) => {
      const catalog = await syncCatalog({ version: options.version });
      await writeCatalogOutputs(options.outDir, catalog);
      stdout.write(
        `synced ${catalog.operations.length} operations and ${catalog.docsEntries.length} docs entries to ${options.outDir}\n`
      );
    });

  const api = program.command('api').description('Raw Google Ads API access');

  api
    .command('invoke')
    .argument('<operationId>', 'Discovery operation id such as customers.campaigns.mutate')
    .requiredOption('--catalog <path>', 'Path to operations.json generated by docs sync')
    .option('--access-token <token>', 'OAuth access token')
    .option('--developer-token <token>', 'Google Ads developer token')
    .option('--login-customer-id <id>', 'Manager account acting on behalf of the target account')
    .option('--linked-customer-id <id>', 'Linked customer id for select product operations')
    .option('--customer-id <id>', 'Convenience alias for path param customerId')
    .option('--path-param <pair...>', 'Extra path param in name=value form')
    .option('--body <json>', 'Inline JSON request body')
    .option('--body-file <path>', 'Path to a JSON request body file')
    .option('--dry-run', 'Print the resolved HTTP request instead of sending it')
    .action(
      async (
        operationId: string,
        options: {
          accessToken?: string;
          body?: string;
          bodyFile?: string;
          catalog: string;
          customerId?: string;
          developerToken?: string;
          dryRun?: boolean;
          linkedCustomerId?: string;
          loginCustomerId?: string;
          pathParam?: string[];
        }
      ) => {
        const operations = await loadOperationsCatalog(options.catalog);
        const operation = operations.find((entry) => entry.operationId === operationId);

        if (!operation) {
          throw new Error(`Unknown operation id: ${operationId}`);
        }

        if (!options.accessToken) {
          throw new Error('--access-token is required');
        }

        if (!options.developerToken) {
          throw new Error('--developer-token is required');
        }

        const pathParams = Object.fromEntries(
          (options.pathParam ?? []).map((pair) => {
            const [key, value] = pair.split('=');

            if (!key || !value) {
              throw new Error(`Invalid --path-param value: ${pair}`);
            }

            return [key, value];
          })
        );

        if (options.customerId) {
          pathParams.customerId = options.customerId;
        }

        const payload =
          options.body !== undefined
            ? JSON.parse(options.body)
            : options.bodyFile
              ? JSON.parse(await readFile(options.bodyFile, 'utf8'))
              : undefined;

        const request = buildGoogleAdsRequest({
          accessToken: options.accessToken,
          developerToken: options.developerToken,
          linkedCustomerId: options.linkedCustomerId,
          loginCustomerId: options.loginCustomerId,
          operation,
          pathParams,
          payload
        });

        if (options.dryRun) {
          stdout.write(`${JSON.stringify(request, null, 2)}\n`);
          return;
        }

        const response = await fetch(request.url, request.init);
        const responseText = await response.text();
        stdout.write(responseText);
      }
    );

  try {
    await program.parseAsync(argv, { from: 'user' });
    return 0;
  } catch (error) {
    if (error instanceof Error) {
      stdout.write(`${error.message}\n`);
    }

    return 1;
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const exitCode = await runCli(process.argv.slice(2));
  process.exit(exitCode);
}
